version: 1
snapshot:
  # percy specific CSS used when rendering snapshots
  # ignoring build_commit block, as it changes everytime !
  percy-css: |
    .build-info.build-commit {
      display: none;
    }

  widths: [1920]
